# Generated by Django 4.1.7 on 2023-03-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmoCRMTokens",
            fields=[
                (
                    "manager_name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Имя менеджера токенов",
                    ),
                ),
                ("access_token", models.TextField(verbose_name="Токен доступа")),
                ("refresh_token", models.TextField(verbose_name="Токен обновления")),
            ],
            options={
                "verbose_name": "Токены доступа amoCRM",
                "verbose_name_plural": "Токены доступа amoCRM",
            },
        ),
    ]
